// HS编码数据库 - 电子设备及配件类（中国海关10位编码）
// 数据来源：中国海关进出口税则，仅供参考，实际申报以海关核定为准
window.HS_DB = [
  // ===== 手机及配件 =====
  {code:"8517130000",name:"智能电话机(智能手机)",en:"Smartphones",cat:"手机及配件",expired:false,kw:"手机 智能手机 phone smartphone cellphone 智能机"},
  {code:"8517140000",name:"其他蜂窝网络手机",en:"Other cellular mobile phones",cat:"手机及配件",expired:false,kw:"手机 phone 功能机 老人机 feature phone"},
  {code:"8517620090",name:"其他数据通讯设备(路由器/调制解调器)",en:"Other data comms equipment(routers/modems)",cat:"手机及配件",expired:false,kw:"路由器 router 调制解调器 modem 网络设备 网关"},
  {code:"8517706000",name:"手机零件(天线/振动马达/听筒)",en:"Mobile phone parts(antenna/vibrator/receiver)",cat:"手机及配件",expired:false,kw:"手机零件 配件 天线 振动马达 听筒 receiver antenna"},
  {code:"8517709000",name:"其他通信设备零件",en:"Other communication equipment parts",cat:"手机及配件",expired:false,kw:"通讯零件 配件 parts communication"},
  {code:"8504402000",name:"手机充电器",en:"Mobile phone chargers",cat:"手机及配件",expired:false,kw:"充电器 charger 手机充电 快充 充电头 adapter"},
  {code:"8504409990",name:"其他电源适配器",en:"Other power adapters",cat:"手机及配件",expired:false,kw:"充电器 adapter 电源适配器 快充头 PD充电器 GaN"},
  {code:"8507600090",name:"锂离子电池/充电宝",en:"Li-ion batteries/Power banks",cat:"手机及配件",expired:false,kw:"充电宝 powerbank 电池 battery 锂电池 移动电源 无线充"},
  {code:"8507600010",name:"手机用锂离子电池",en:"Li-ion batteries for mobile phones",cat:"手机及配件",expired:false,kw:"手机电池 电池 锂电池 battery phone"},
  {code:"8544422900",name:"数据线/USB线",en:"Data cables/USB cables",cat:"手机及配件",expired:false,kw:"数据线 cable USB 线 data 充电线 Type-C Lightning"},
  {code:"8544429000",name:"其他绝缘电线",en:"Other insulated wires",cat:"手机及配件",expired:false,kw:"电线 wire 绝缘 wire cable"},
  {code:"3926900000",name:"其他塑料制品(含手机壳/手机支架)",en:"Other plastic articles(phone cases/stands)",cat:"手机及配件",expired:false,kw:"手机壳 case 手机套 手机支架 手机配件 phone holder stand"},
  {code:"8543709990",name:"手机支架/车载手机支架(电气式)",en:"Phone holders/Car mounts(electric)",cat:"手机及配件",expired:false,kw:"手机支架 车载支架 car mount phone holder 无线充支架"},
  {code:"9007200000",name:"手机镜头/外接镜头",en:"Phone camera lenses",cat:"手机及配件",expired:false,kw:"手机镜头 外接镜头 lens camera phone"},
  {code:"8525802900",name:"手机摄像头模组",en:"Phone camera modules",cat:"手机及配件",expired:false,kw:"摄像头 模组 camera module 手机镜头"},
  {code:"8517610000",name:"基站/通信设备",en:"Base stations/Communication equipment",cat:"手机及配件",expired:false,kw:"基站 通信设备 base station 信号放大器"},

  // ===== 电脑及配件 =====
  {code:"8471300000",name:"便携式电脑(笔记本/平板)",en:"Portable computers(laptops/tablets)",cat:"电脑及配件",expired:true,kw:"笔记本 电脑 laptop computer 便携 平板 tablet"},
  {code:"8471410000",name:"微型机(含CPU+输入输出部件)",en:"Microcomputers(with CPU+I/O)",cat:"电脑及配件",expired:false,kw:"电脑 computer 台式 微型 主机 mini PC"},
  {code:"8471414000",name:"微型机(其他)",en:"Microcomputers(other)",cat:"电脑及配件",expired:false,kw:"电脑 computer 微型 主机"},
  {code:"8471492000",name:"其他电脑(大型/中型)",en:"Other computers",cat:"电脑及配件",expired:false,kw:"电脑 computer 服务器 server"},
  {code:"8471494000",name:"其他电脑",en:"Other computers",cat:"电脑及配件",expired:false,kw:"电脑 computer 服务器 server"},
  {code:"8471499100",name:"其他电脑",en:"Other computers",cat:"电脑及配件",expired:false,kw:"电脑 computer"},
  {code:"8471499900",name:"其他电脑(未列名)",en:"Other computers N.E.S.",cat:"电脑及配件",expired:false,kw:"电脑 computer"},
  {code:"8471504090",name:"其他数据处理设备",en:"Other data processing equipment",cat:"电脑及配件",expired:false,kw:"电脑 computer 数据处理 工控机"},
  {code:"8471607100",name:"键盘",en:"Keyboards",cat:"电脑及配件",expired:false,kw:"键盘 keyboard 机械键盘 无线键盘"},
  {code:"8471607200",name:"鼠标器",en:"Mice",cat:"电脑及配件",expired:false,kw:"鼠标 mouse 无线鼠标 游戏鼠标"},
  {code:"8471609000",name:"其他输入输出部件",en:"Other input/output units",cat:"电脑及配件",expired:false,kw:"电脑配件 输入输出 触控板 扫描仪 scanner"},
  {code:"8473301000",name:"电脑零部件(主板/显卡/内存)",en:"Computer parts(mobo/GPU/RAM)",cat:"电脑及配件",expired:false,kw:"主板 显卡 内存 RAM GPU motherboard 电脑配件 零件 CPU"},
  {code:"8473309000",name:"其他电脑零部件",en:"Other computer parts",cat:"电脑及配件",expired:false,kw:"电脑 零件 parts 配件 computer 硬盘 SSD 散热器"},
  {code:"8471701000",name:"硬盘驱动器",en:"Hard disk drives",cat:"电脑及配件",expired:false,kw:"硬盘 HDD 机械硬盘 hard disk"},
  {code:"8471702000",name:"固态硬盘(SSD)",en:"Solid state drives(SSD)",cat:"电脑及配件",expired:false,kw:"固态硬盘 SSD 固态 solid state"},
  {code:"8471703000",name:"闪存型存储(U盘/存储卡)",en:"Flash storage(USB flash/memory cards)",cat:"电脑及配件",expired:false,kw:"U盘 USB flash 存储卡 SD卡 TF卡 memory card"},
  {code:"8523512090",name:"U盘/固态存储设备",en:"USB flash drives/SSD",cat:"电脑及配件",expired:false,kw:"U盘 USB flash 存储盘 storage 移动硬盘"},
  {code:"7616999000",name:"铝制其他制品(电脑机壳/配件)",en:"Aluminum articles(computer cases)",cat:"电脑及配件",expired:false,kw:"电脑机壳 机壳 配件 aluminum case 机箱"},
  {code:"8528521090",name:"电子显示器/显示器",en:"Electronic displays/monitors",cat:"电脑及配件",expired:false,kw:"显示器 monitor display 屏幕 电竞显示器 曲面屏"},
  {code:"8528590010",name:"投影仪",en:"Projectors",cat:"电脑及配件",expired:false,kw:"投影仪 projector 投影 家用投影 便携投影"},
  {code:"8528691000",name:"其他显示器",en:"Other displays",cat:"电脑及配件",expired:false,kw:"显示器 display monitor 屏幕"},
  {code:"8471900090",name:"其他数据处理设备配件",en:"Other data processing accessories",cat:"电脑及配件",expired:false,kw:"电脑配件 配件 集线器 hub 扩展坞 docking station"},

  // ===== 音频设备 =====
  {code:"8518300090",name:"耳机/蓝牙耳机/头戴式耳机",en:"Headphones/Bluetooth earphones",cat:"音频设备",expired:false,kw:"耳机 earphone headphone bluetooth TWS 真无线 头戴式 入耳式"},
  {code:"8518300010",name:"耳机(耳塞式)",en:"Earphones/In-ear headphones",cat:"音频设备",expired:false,kw:"耳机 耳塞 earphone 入耳式 in-ear"},
  {code:"8518220090",name:"音箱/蓝牙音箱/智能音箱",en:"Speakers/Bluetooth speakers",cat:"音频设备",expired:false,kw:"音箱 speaker bluetooth 音响 蓝牙音箱 智能音箱 便携音箱"},
  {code:"8518210000",name:"单喇叭音箱",en:"Single loudspeakers",cat:"音频设备",expired:false,kw:"喇叭 speaker 扬声器 单喇叭"},
  {code:"8518290000",name:"其他多喇叭音箱/音响系统",en:"Other multi-speaker systems",cat:"音频设备",expired:false,kw:"音箱 speaker 音响系统 家庭影院 soundbar"},
  {code:"8518100000",name:"传声器(麦克风)",en:"Microphones",cat:"音频设备",expired:false,kw:"麦克风 mic 话筒 领夹麦 收音麦 microphone"},
  {code:"8518400090",name:"耳机放大器/音频放大器",en:"Headphone amplifiers/Audio amplifiers",cat:"音频设备",expired:false,kw:"耳放 功放 amplifier 音频放大器"},
  {code:"8519812000",name:"MP3播放器/数字音频播放器",en:"MP3 players/Digital audio players",cat:"音频设备",expired:false,kw:"MP3 播放器 随身听 player music 无损播放器"},
  {code:"8525801390",name:"录音笔/数码录音器",en:"Voice recorders/Digital recorders",cat:"音频设备",expired:false,kw:"录音笔 录音器 recorder 录音设备"},

  // ===== 摄影摄像设备 =====
  {code:"8525801290",name:"其他摄像机/摄像头/运动相机",en:"Other cameras/webcams/Action cams",cat:"摄影摄像",expired:false,kw:"摄像头 camera 摄像 监控 surveillance 运动相机 运动 cam  webcam"},
  {code:"8525801100",name:"电视摄像机/专业摄像机",en:"TV cameras/Professional cameras",cat:"摄影摄像",expired:false,kw:"摄像机 camera 专业摄像机 摄影机"},
  {code:"8525802100",name:"数码相机/单反相机",en:"Digital cameras/DSLR",cat:"摄影摄像",expired:false,kw:"数码相机 单反 camera DSLR 微单 相机 mirrorless"},
  {code:"8525802900",name:"其他数码相机",en:"Other digital cameras",cat:"摄影摄像",expired:false,kw:"数码相机 相机 camera 卡片机 拍立得"},
  {code:"8525803100",name:"手机摄像头模组",en:"Phone camera modules",cat:"摄影摄像",expired:false,kw:"摄像头模组 镜头模组 camera module"},
  {code:"8525803900",name:"其他摄像模块",en:"Other camera modules",cat:"摄影摄像",expired:false,kw:"摄像头 模组 camera module"},
  {code:"9002110000",name:"相机镜头(物镜)",en:"Camera lenses(objectives)",cat:"摄影摄像",expired:false,kw:"镜头 lens 相机镜头 单反镜头 微单镜头"},
  {code:"9002190000",name:"其他镜头/镜头配件",en:"Other lenses/Lens accessories",cat:"摄影摄像",expired:false,kw:"镜头 lens 滤镜 转接环 filter 镜头配件"},
  {code:"9006919900",name:"照相机用其他零件",en:"Other camera parts",cat:"摄影摄像",expired:false,kw:"相机配件 三脚架 tripod 云台 稳定器 gimbal 电池 充电器"},
  {code:"9007200000",name:"其他视频录制设备/运动相机",en:"Other video recording equipment/Action cams",cat:"摄影摄像",expired:false,kw:"运动相机 运动相机 gopro action cam 运动摄像机"},
  {code:"8525801900",name:"其他视频设备",en:"Other video equipment",cat:"摄影摄像",expired:false,kw:"视频设备 录像机 video camera"},

  // ===== 智能家居 & 穿戴设备 =====
  {code:"8517691000",name:"智能手表/智能手环",en:"Smart watches/Smart bands",cat:"智能穿戴",expired:false,kw:"智能手表 手表 watch smartwatch 手环 band 智能手环 运动手表"},
  {code:"9102120000",name:"电子手表/智能手表",en:"Electronic watches/Smart watches",cat:"智能穿戴",expired:false,kw:"电子表 手表 watch 智能手表 smartwatch quartz"},
  {code:"8517699000",name:"其他通信设备(智能眼镜等)",en:"Other comms devices(smart glasses etc)",cat:"智能穿戴",expired:false,kw:"智能眼镜 眼镜 glasses smart glasses VR AR 头显"},
  {code:"8543709990",name:"智能手环/智能穿戴设备",en:"Smart bands/Wearable devices",cat:"智能穿戴",expired:false,kw:"智能手环 手环 band 穿戴设备 wearable 智能戒指 智能项链"},
  {code:"9013803000",name:"VR/AR眼镜/头戴显示设备",en:"VR/AR headsets/Head mounted displays",cat:"智能穿戴",expired:false,kw:"VR AR 眼镜 头显 headset 虚拟现实 增强现实 meta quest"},
  {code:"8517121000",name:"对讲机",en:"Walkie-talkies",cat:"智能穿戴",expired:false,kw:"对讲机 walkie talkie 对讲 手台 radio"},

  // ===== 智能家居 =====
  {code:"8543709990",name:"智能家居设备(智能插座/灯泡/开关)",en:"Smart home devices(sockets/bulbs/switches)",cat:"智能家居",expired:false,kw:"智能家居 smart home 智能插座 智能开关 智能灯泡 网关 hub"},
  {code:"9405421000",name:"LED灯具/智能灯/台灯",en:"LED lights/Smart lamps/Desk lamps",cat:"智能家居",expired:false,kw:"LED灯 灯 lamp light 照明 灯具 台灯 智能灯 氛围灯 灯带"},
  {code:"9405190000",name:"LED灯串/装饰灯/氛围灯",en:"LED string lights/Ambient lights",cat:"智能家居",expired:false,kw:"灯串 string 装饰灯 彩灯 氛围灯 霓虹灯 neon"},
  {code:"8536500000",name:"开关/插座/智能插座",en:"Switches/Sockets/Smart sockets",cat:"智能家居",expired:false,kw:"开关 switch 插座 socket 智能插座 排插 插线板 power strip"},
  {code:"8536610000",name:"插头/插座(电压≤1000V)",en:"Plugs/Sockets(≤1000V)",cat:"智能家居",expired:false,kw:"插头 插座 plug socket 电源插座"},
  {code:"8537101100",name:"低压控制板/控制开关",en:"Low voltage control panels",cat:"智能家居",expired:false,kw:"控制板 控制面板 control panel 低压控制"},
  {code:"8519813000",name:"智能音箱/语音助手设备",en:"Smart speakers/Voice assistants",cat:"智能家居",expired:false,kw:"智能音箱 语音助手 echo dot alexa google home 小爱 天猫精灵"},
  {code:"8528521090",name:"智能屏/带屏音箱",en:"Smart displays/Screen speakers",cat:"智能家居",expired:false,kw:"智能屏 带屏音箱 smart display 小度在家 echo show"},
  {code:"9031809000",name:"智能传感器/温湿度传感器",en:"Smart sensors/Temp/humidity sensors",cat:"智能家居",expired:false,kw:"传感器 sensor 温度 湿度 温湿度 人体感应 门窗传感器 motion"},
  {code:"8531801000",name:"防盗报警器/智能门锁",en:"Burglar alarms/Smart door locks",cat:"智能家居",expired:false,kw:"报警器 alarm 智能门锁 door lock 门锁 指纹锁 密码锁"},
  {code:"8531200000",name:"LED指示灯/指示灯面板",en:"LED indicator panels",cat:"智能家居",expired:false,kw:"LED 指示灯 面板 panel 指示灯"},

  // ===== 网络设备 =====
  {code:"8517621000",name:"路由器/无线AP",en:"Routers/Wireless APs",cat:"网络设备",expired:false,kw:"路由器 router 无线AP 网关 gateway 交换机 wifi6  mesh"},
  {code:"8517622000",name:"调制解调器/光猫",en:"Modems/ONT",cat:"网络设备",expired:false,kw:"调制解调器 modem 光猫 光纤猫 ONT"},
  {code:"8517623000",name:"网络交换机",en:"Network switches",cat:"网络设备",expired:false,kw:"交换机 switch 网络交换机 poe交换机"},
  {code:"8517629000",name:"其他数据通信设备",en:"Other data communication equipment",cat:"网络设备",expired:false,kw:"网络设备 网卡 网桥 中继器 信号放大器 wifi extender"},
  {code:"8544700000",name:"光纤/光缆",en:"Optical fibers/Cables",cat:"网络设备",expired:false,kw:"光纤 光缆 fiber optic cable 网线"},
  {code:"8544421900",name:"网线/网络连接线",en:"Ethernet cables/Network cables",cat:"网络设备",expired:false,kw:"网线 网络线 ethernet cable cat5 cat6 网线 cable"},
  {code:"8523520000",name:"智能卡/存储卡/网卡",en:"Smart cards/Memory cards/Network cards",cat:"网络设备",expired:false,kw:"网卡 智能卡 network card NIC 存储卡 SD card"},

  // ===== 游戏设备 =====
  {code:"9504500000",name:"电子游戏机/游戏主机/手柄",en:"Video game consoles/Controllers",cat:"游戏设备",expired:false,kw:"游戏机 game console 手柄 controller ps5 xbox switch 游戏主机 掌机"},
  {code:"9504509100",name:"电子游戏机零件",en:"Video game console parts",cat:"游戏设备",expired:false,kw:"游戏机配件 游戏手柄 摇杆 controller 游戏配件"},
  {code:"9504509900",name:"其他电子游戏机配件",en:"Other video game accessories",cat:"游戏设备",expired:false,kw:"游戏配件 游戏机配件 游戏卡带 game card 游戏光盘"},
  {code:"8471609000",name:"游戏键盘/游戏鼠标/电竞外设",en:"Gaming keyboard/Gaming mouse/Esports peripherals",cat:"游戏设备",expired:false,kw:"游戏键盘 游戏鼠标 电竞 外设 gaming 机械键盘 游戏耳机"},
  {code:"9504409000",name:"纸牌/桌游/卡牌游戏",en:"Card games/Board games",cat:"游戏设备",expired:false,kw:"纸牌 桌游 card game board 桌游 卡牌 扑克 poker"},
  {code:"9504200000",name:"棋类游戏",en:"Chess/Board games",cat:"游戏设备",expired:false,kw:"棋 象棋 chess board 围棋 五子棋"},

  // ===== 电子配件/周边 =====
  {code:"8542390000",name:"集成电路/芯片",en:"Integrated circuits/Chips",cat:"电子配件",expired:false,kw:"芯片 IC 集成电路 chip 处理器 CPU GPU MCU"},
  {code:"8542310000",name:"处理器及控制器",en:"Processors and controllers",cat:"电子配件",expired:false,kw:"处理器 CPU GPU 芯片 processor controller"},
  {code:"8542320000",name:"存储器",en:"Memory",cat:"电子配件",expired:false,kw:"存储器 内存 RAM ROM flash 存储芯片 memory"},
  {code:"8504500000",name:"变频器/变压器/电源模块",en:"Inverters/Transformers/Power modules",cat:"电子配件",expired:false,kw:"变频器 inverter 变压器 transformer 电源模块 降压模块"},
  {code:"8504319000",name:"其他变压器",en:"Other transformers",cat:"电子配件",expired:false,kw:"变压器 transformer 电源"},
  {code:"8504401400",name:"开关电源/电源模块",en:"Switching power supplies/Power modules",cat:"电子配件",expired:false,kw:"开关电源 电源模块 power supply 模块电源"},
  {code:"8533219000",name:"电阻器/电位器",en:"Resistors/Potentiometers",cat:"电子配件",expired:false,kw:"电阻 resistor 电位器 电子元件"},
  {code:"8533310000",name:"电容器",en:"Capacitors",cat:"电子配件",expired:false,kw:"电容 capacitor 电解电容 陶瓷电容 电子元件"},
  {code:"8541100000",name:"二极管/发光二极管LED",en:"Diodes/LEDs",cat:"电子配件",expired:false,kw:"二极管 diode LED 发光二极管 电子元件"},
  {code:"8541210000",name:"三极管/晶体管",en:"Transistors",cat:"电子配件",expired:false,kw:"三极管 晶体管 transistor MOS管 电子元件"},
  {code:"8542900000",name:"其他半导体器件",en:"Other semiconductor devices",cat:"电子配件",expired:false,kw:"半导体 芯片 电子元件 semiconductor"},
  {code:"8536900000",name:"连接器/接插件",en:"Connectors/Plugs",cat:"电子配件",expired:false,kw:"连接器 connector 接插件 排针 端子 接口"},
  {code:"8544300000",name:"汽车点火线/电缆/线束",en:"Vehicle ignition cables/Wire harness",cat:"电子配件",expired:false,kw:"线束 电缆 cable 点火线 汽车线束 wire harness"},
  {code:"8544411000",name:"同轴电缆/射频线",en:"Coaxial cables/RF cables",cat:"电子配件",expired:false,kw:"同轴电缆 coaxial cable 射频线 RF线"},
  {code:"8546100000",name:"绝缘子/绝缘件",en:"Insulators",cat:"电子配件",expired:false,kw:"绝缘子 绝缘件 insulator 绝缘"},
  {code:"8547200000",name:"电路板/PCB板",en:"Printed circuit boards/PCB",cat:"电子配件",expired:false,kw:"电路板 PCB 线路板 印刷电路板 主板 PCBA"},
  {code:"8543900000",name:"其他电气设备零件",en:"Other electrical equipment parts",cat:"电子配件",expired:false,kw:"电气设备 配件 零件 electrical parts"},
  {code:"8548100000",name:"废碎料/电气废料",en:"Electrical waste/scrap",cat:"电子配件",expired:false,kw:"电子废料 废电路板 废铜 scrap"},

  // ===== 小家电 & 个护电器 =====
  {code:"8516500000",name:"微波炉/光波炉",en:"Microwave ovens",cat:"个护小家电",expired:false,kw:"微波炉 microwave 微波 光波炉"},
  {code:"8516603000",name:"电饭煲/电压力锅",en:"Rice cookers/Electric pressure cookers",cat:"个护小家电",expired:false,kw:"电饭煲 cooker 电压力锅 电饭锅 cooking"},
  {code:"8516710000",name:"咖啡机/胶囊咖啡机",en:"Coffee makers/Capsule coffee machines",cat:"个护小家电",expired:false,kw:"咖啡机 coffee maker 咖啡 胶囊咖啡机"},
  {code:"8516790000",name:"其他电热器具(电热水壶/面包机等)",en:"Other electro-thermic appliances(kettle/toaster etc)",cat:"个护小家电",expired:false,kw:"电热 heater 电热水壶 kettle 面包机 toaster 三明治机 空气炸锅 air fryer"},
  {code:"8418102000",name:"冰箱/冷藏柜/冰柜",en:"Refrigerators/Freezers",cat:"个护小家电",expired:false,kw:"冰箱 refrigerator 冷冻 freezer 冰柜 迷你冰箱"},
  {code:"8421210000",name:"净水器/过滤器/饮水机",en:"Water purifiers/Filters/Water dispensers",cat:"个护小家电",expired:false,kw:"净水器 净化 water purifier filter 过滤 饮水机"},
  {code:"8474200000",name:"搅拌机/榨汁机/粉碎机",en:"Mixers/Juicers/Crushers",cat:"个护小家电",expired:false,kw:"搅拌机 mixer 榨汁机 juicer 粉碎机 blender 破壁机"},
  {code:"8423810000",name:"厨房秤/电子秤/体重秤",en:"Kitchen scales/Electronic scales/Body scales",cat:"个护小家电",expired:false,kw:"秤 厨房秤 电子秤 scale weighing 体重秤 体脂秤"},
  {code:"8509800000",name:"其他电动食品加工器",en:"Other electric food processors",cat:"个护小家电",expired:false,kw:"食品加工器 料理机 food processor 绞肉机 打蛋器"},
  {code:"8510100000",name:"电动剃须刀",en:"Electric shavers",cat:"个护小家电",expired:false,kw:"剃须刀 shaver 电动剃须刀 刮胡刀"},
  {code:"8510200000",name:"电动理发器/电推剪",en:"Electric hair clippers",cat:"个护小家电",expired:false,kw:"理发器 电推剪 clipper 剃头刀 理发剪"},
  {code:"8510900000",name:"其他电动毛发护理器具",en:"Other electric hair care appliances",cat:"个护小家电",expired:false,kw:"吹风机 电吹风 hair dryer 卷发棒 直发器 脱毛仪 hair removal"},
  {code:"8516310000",name:"电吹风机/电吹风",en:"Electric hair dryers",cat:"个护小家电",expired:false,kw:"吹风机 电吹风 hair dryer 风筒"},
  {code:"8516320000",name:"其他电动毛发护理器具",en:"Other electric hair care appliances",cat:"个护小家电",expired:false,kw:"卷发棒 直发器 curling iron 美发 造型 hair styler"},
  {code:"8509401000",name:"电动牙刷",en:"Electric toothbrushes",cat:"个护小家电",expired:false,kw:"电动牙刷 toothbrush 牙刷 冲牙器 水牙线"},
  {code:"8509409000",name:"其他口腔卫生器具",en:"Other oral hygiene appliances",cat:"个护小家电",expired:false,kw:"冲牙器 水牙线 oral irrigator 洗牙器"},
  {code:"9603219000",name:"牙刷(手动)",en:"Toothbrushes(manual)",cat:"个护小家电",expired:false,kw:"牙刷 toothbrush 牙刷 手动牙刷"},
  {code:"3306200000",name:"牙线/口腔护理",en:"Dental floss/Oral care",cat:"个护小家电",expired:false,kw:"牙线 口腔 dental floss oral 漱口水"},

  // ===== 汽车电子 =====
  {code:"8708299000",name:"汽车零配件(车身附件/电子)",en:"Motor vehicle parts(body/electronics)",cat:"汽车电子",expired:false,kw:"汽车配件 零件 auto parts 汽配 汽车 车机 车载"},
  {code:"8708999990",name:"其他汽车零件",en:"Other vehicle parts",cat:"汽车电子",expired:false,kw:"汽车零件 parts auto 汽车 汽配"},
  {code:"8544300000",name:"汽车点火线/电缆/线束",en:"Vehicle ignition cables/Wire harness",cat:"汽车电子",expired:false,kw:"点火线 电缆 汽车线束 wire harness 车载线"},
  {code:"8512200000",name:"汽车照明设备/车灯",en:"Automotive lighting equipment/Headlights",cat:"汽车电子",expired:false,kw:"车灯 大灯 headlight 汽车灯 LED大灯 雾灯"},
  {code:"8512900000",name:"其他汽车电气设备",en:"Other automotive electrical equipment",cat:"汽车电子",expired:false,kw:"汽车电气 车载电器 汽车电子 auto electronics"},
  {code:"8527920000",name:"汽车收音机/车载导航",en:"Car radios/Car navigation",cat:"汽车电子",expired:false,kw:"车载导航 车机 导航 navigation car radio 中控屏"},
  {code:"8525801290",name:"行车记录仪/车载摄像头",en:"Dash cams/Car cameras",cat:"汽车电子",expired:false,kw:"行车记录仪 记录仪 dash cam 车载摄像头 倒车影像"},
  {code:"9029102000",name:"汽车测速仪/胎压监测",en:"Car speedometers/TPMS",cat:"汽车电子",expired:false,kw:"胎压监测 TPMS 测速仪 汽车仪表 胎压"},
  {code:"4011100000",name:"新充气轮胎(轿车)",en:"New pneumatic tires(passenger cars)",cat:"汽车电子",expired:false,kw:"轮胎 tire tyre 轮胎 车胎 car tire"},
  {code:"8543709990",name:"车载充电器/车载逆变器",en:"Car chargers/Car inverters",cat:"汽车电子",expired:false,kw:"车载充电器 车充 car charger 逆变器 inverter 车载"},

  // ===== 办公电子 =====
  {code:"8471300000",name:"平板/平板电脑",en:"Tablets/Tablet computers",cat:"办公电子",expired:true,kw:"平板 tablet 平板电脑 ipad 平板"},
  {code:"8471605000",name:"扫描仪",en:"Scanners",cat:"办公电子",expired:false,kw:"扫描仪 scanner 扫描 高拍仪"},
  {code:"8471606000",name:"打印机",en:"Printers",cat:"办公电子",expired:false,kw:"打印机 printer 激光打印机 喷墨打印机 标签打印机"},
  {code:"8471609000",name:"其他输入输出设备",en:"Other I/O devices",cat:"办公电子",expired:false,kw:"输入输出 绘图仪 数位板 手写板 drawing tablet"},
  {code:"8443319000",name:"其他印刷机/3D打印机",en:"Other printers/3D printers",cat:"办公电子",expired:false,kw:"3D打印机 3d printer 打印"},
  {code:"8472909000",name:"其他办公室机器",en:"Other office machines",cat:"办公电子",expired:false,kw:"碎纸机 装订机 塑封机 办公设备 office"},
  {code:"8472100000",name:"打字机/字处理机",en:"Typewriters/Word processors",cat:"办公电子",expired:false,kw:"打字机 typewriter"},
  {code:"8472210000",name:"计算器/电子计算器",en:"Calculators/Electronic calculators",cat:"办公电子",expired:false,kw:"计算器 calculator 计算机 科学计算器"},
  {code:"9610000000",name:"黑板/白板/画板",en:"Blackboards/Whiteboards",cat:"办公电子",expired:false,kw:"黑板 白板 画板 board blackboard whiteboard 磁吸白板"},
];
